### ISSUE TITLE
RawData로 pandas를 활용한 표 만들기

### ISSUE THREAD

**Issue by SeyeonJang** [SeyeonJang/Data-Analysis-Study#1]
### 📊 데이터 분석 자료
- **데이콘 이커머스 고객 세분화 분석 아이디어 경진대회** [데이터](https://dacon.io/competitions/official/236222/data)
  <img width="80%" alt="image" src="https://github.com/SeyeonJang/Data-Analysis-Study/assets/47477205/8fdecff7-11f8-4b27-8b9c-0b41b32ab801">

### ✅ To-do
- [ ] 분석해보고 싶은 데이터에서 필요한 Raw Data 추출
  - 고객의 지역에 따른 월별 매출 실적
  - 제품 카테고리별 쿠폰 사용 비율
  - 구입 평균 금액 대비 쿠폰 활용 비율
- [ ] Python pandas 라이브러리 설치 & 환경 세팅
- [ ] pandas로 Raw Data를 활용한 표 만들기

### ✨ 참고 사항
- [Pandas_Cheet_Sheet.pdf](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf) (표 만들기 안내 도구)
- [Chart Visualization](https://pandas.pydata.org/docs/user_guide/visualization.html) (차트 시각화 안내 pandas 공식 홈페이지)
