### ISSUE TITLE
[KPI 도출 비즈니스 전략 아이디어 경진대회] 핵심 성과 지표 도출

### ISSUE THREAD

**Issue by SeyeonJang** [SeyeonJang/Data-Analysis-Study#4]
### 주제
데이터를 분석하여 핵심 성과 지표(KPI : ex. MAU, CLV 등)를 도출 및 비즈니스를 위한 전략 방안 제시
### 설명
비즈니스 환경에서 파악할 수 있는 KPI(ex. MAU, CLV 등)를 도출해 이를 기반으로 KPI를 향상시키기 위한  아이디어를 제시해주세요.
또한, 참가자 여러분은 데이터 분석을 통해 자신만의 독창적인 KPI를 직접 정의하고, 이를 기반으로 아이디어를 제시하실 수 있습니다.

### 📊 [데이터 분석 자료](https://dacon.io/competitions/official/236248/data)
- **브라질** 이커머스 회사의 데이터
![image](https://github.com/SeyeonJang/Data-Analysis-Study/assets/47477205/f8d63dab-247b-4fe8-b242-0af79e762921)

### ✅ To-do
- 제안할 KPI = **고객 평균 주문 가치** (AOV, Average Order Value)
- [x] 월별 매출액
- [x] 월별 평균 주문 가치(Average Order Value, AOV)
- [x] 월별 주문 건수
- [x] 구매 당 평균 상품 개수
- [x] 구매 당 평균 구매 금액
- [x] 구매 당 상품 개수 (Order_id 기준)
- [x] 인당 평균 구매 상품 수 (Customer_id 기준)
- [x] 인당 평균 구매 가치 (AOV) (Customer_id 기준)
- [x] 평균 AOV를 기준으로 높은 / 낮은 그룹을 나눠서 판매량 카테고리 순위 확인
- [x] AOV 그룹별 사용한 결제 수단 확인
- [x] 평균 AOV 0~10인 그룹의 재구매율, 재구매 기간 확인
- [x] 평균 AOV 10~60인 그룹의 주문 당 상품 수, 재구매율 확인
- [x] 평균 AOV 200~300인 그룹의 할부 개월 수 확인

### 📸 스크린샷

![image](https://github.com/SeyeonJang/Data-Analysis-Study/assets/47477205/6070cd80-8b06-4893-b7fd-1d95431e98a4)
![image](https://github.com/SeyeonJang/Data-Analysis-Study/assets/47477205/6eb6b2b8-2152-4510-b606-08be92cd7a45)

<img width="32%" alt="image" src="https://github.com/SeyeonJang/Data-Analysis-Study/assets/47477205/54579a93-0e68-4ba6-8958-9d7ec7ac1525">
<img width="32%" alt="image" src="https://github.com/SeyeonJang/Data-Analysis-Study/assets/47477205/f3af0461-7b98-4417-857a-ec4abde6c8c4">
<img width="32%" alt="image" src="https://github.com/SeyeonJang/Data-Analysis-Study/assets/47477205/4a5eb795-236c-4b51-a574-2cc11c34d67c">
